import { Skill } from "./skills";

export const skills: Skill[] = [
  // 內容行銷 — Content Marketing
  {
    id: "1.01",
    category: "內容行銷",
    name: "寫作助理 ─ 靈感發想",
    description:
      "Input: 主題關鍵字、目標受眾、內容類型（文章/貼文/電子報）\nProcess: 透過 AI 腦力激盪產出多角度切入方向，並排序吸引力\nOutput: 5–10 個標題方向 + 每個方向的 2–3 句摘要說明",
    input: "主題關鍵字、目標受眾、內容類型（文章/貼文/電子報）",
    process: "透過 AI 腦力激盪產出多角度切入方向，並排序吸引力",
    output: "5–10 個標題方向 + 每個方向的 2–3 句摘要說明",
    synergy: ["1.01", "1.02", "1.03"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    link: "https://chatgpt.com/g/g-example-101",
    updatedAt: "2025-11-01",
  },
  {
    id: "1.02",
    category: "內容行銷",
    name: "寫作助理 ─ 初稿生成",
    description:
      "Input: 選定的標題方向、大綱草稿、品牌語氣指南\nProcess: 依照結構生成文章初稿，保留人性化語調，避免 AI 腔\nOutput: 800–1500 字完整初稿，含引言、主體段落、結論",
    input: "選定的標題方向、大綱草稿、品牌語氣指南",
    process: "依照結構生成文章初稿，保留人性化語調，避免 AI 腔",
    output: "800–1500 字完整初稿，含引言、主體段落、結論",
    synergy: ["1.01", "1.02", "1.03"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    link: "https://claude.ai/project/example-102",
    updatedAt: "2025-11-05",
  },
  {
    id: "1.03",
    category: "內容行銷",
    name: "寫作助理 ─ 潤稿與SEO優化",
    description:
      "Input: 文章初稿、目標關鍵字列表、SEO 指標目標\nProcess: 優化標題、段落結構、關鍵字密度，並強化可讀性\nOutput: SEO 優化後版本 + 關鍵字建議 + 可讀性評分",
    input: "文章初稿、目標關鍵字列表、SEO 指標目標",
    process: "優化標題、段落結構、關鍵字密度，並強化可讀性",
    output: "SEO 優化後版本 + 關鍵字建議 + 可讀性評分",
    synergy: ["1.01", "1.02", "1.03"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-11-10",
  },
  {
    id: "1.04",
    category: "內容行銷",
    name: "社群貼文生成器",
    description:
      "Input: 核心訊息、平台（LinkedIn/IG/FB）、貼文目的\nProcess: 依各平台格式、字數限制與語調生成對應版本\nOutput: 各平台貼文草稿 + Hashtag 建議 + 最佳發布時機",
    input: "核心訊息、平台（LinkedIn/IG/FB）、貼文目的",
    process: "依各平台格式、字數限制與語調生成對應版本",
    output: "各平台貼文草稿 + Hashtag 建議 + 最佳發布時機",
    synergy: ["1.04", "1.05"],
    platform: "gpt",
    status: "Done",
    author: "Amy",
    link: "https://chatgpt.com/g/g-example-104",
    updatedAt: "2025-11-15",
  },
  {
    id: "1.05",
    category: "內容行銷",
    name: "電子報撰寫助理",
    description:
      "Input: 本期主題、訂閱者畫像、往期電子報風格樣本\nProcess: 生成符合品牌調性的電子報結構，含主題句、正文、CTA\nOutput: 完整電子報草稿 + 主旨列建議（A/B 測試版本）",
    input: "本期主題、訂閱者畫像、往期電子報風格樣本",
    process: "生成符合品牌調性的電子報結構，含主題句、正文、CTA",
    output: "完整電子報草稿 + 主旨列建議（A/B 測試版本）",
    synergy: ["1.04", "1.05"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-11-20",
  },
  {
    id: "1.06",
    category: "內容行銷",
    name: "影片腳本生成器",
    description:
      "Input: 影片主題、時長（分鐘）、目標平台（YouTube/Reels）\nProcess: 生成分鏡結構腳本，含鉤子開場、主體內容、結尾CTA\nOutput: 逐段腳本 + 分鏡說明 + 視覺建議",
    input: "影片主題、時長（分鐘）、目標平台（YouTube/Reels）",
    process: "生成分鏡結構腳本，含鉤子開場、主體內容、結尾CTA",
    output: "逐段腳本 + 分鏡說明 + 視覺建議",
    synergy: ["1.06"],
    platform: "gpt",
    status: "WIP",
    author: "Peter",
    updatedAt: "2025-12-01",
  },
  {
    id: "1.07",
    category: "內容行銷",
    name: "內容日曆規劃師",
    description:
      "Input: 月度主題、發布頻率、平台清單、行銷目標\nProcess: 生成30天內容行事曆，平衡教育/娛樂/銷售內容比例\nOutput: 月度內容日曆表格 + 每篇摘要 + 平台分配",
    input: "月度主題、發布頻率、平台清單、行銷目標",
    process: "生成30天內容行事曆，平衡教育/娛樂/銷售內容比例",
    output: "月度內容日曆表格 + 每篇摘要 + 平台分配",
    synergy: ["1.07"],
    platform: "gpt",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-12-05",
  },
  {
    id: "1.08",
    category: "內容行銷",
    name: "競品內容分析師",
    description:
      "Input: 競品名稱清單、分析維度（主題/格式/頻率/互動）\nProcess: 系統化分析競品內容策略，找出差異點與機會\nOutput: 競品分析報告 + 差異化機會建議 + 內容地圖缺口",
    input: "競品名稱清單、分析維度（主題/格式/頻率/互動）",
    process: "系統化分析競品內容策略，找出差異點與機會",
    output: "競品分析報告 + 差異化機會建議 + 內容地圖缺口",
    synergy: ["1.08"],
    platform: "gemini",
    status: "Not started",
    author: "Peter",
    updatedAt: "2025-12-10",
  },

  // 職涯 — Career
  {
    id: "2.01",
    category: "職涯",
    name: "履歷優化助理",
    description:
      "Input: 現有履歷（PDF/文字）、目標職位描述（JD）\nProcess: 比對 JD 關鍵字，重構履歷成就描述（STAR格式），強化 ATS 通過率\nOutput: 優化後履歷 + 關鍵字匹配報告 + 修改建議說明",
    input: "現有履歷（PDF/文字）、目標職位描述（JD）",
    process: "比對 JD 關鍵字，重構履歷成就描述（STAR格式），強化 ATS 通過率",
    output: "優化後履歷 + 關鍵字匹配報告 + 修改建議說明",
    synergy: ["2.01", "2.02", "2.03"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    link: "https://claude.ai/project/example-201",
    updatedAt: "2025-10-15",
  },
  {
    id: "2.02",
    category: "職涯",
    name: "求職信生成器",
    description:
      "Input: 優化後履歷、目標公司資訊、JD 全文\nProcess: 生成客製化求職信，突顯匹配度並展現文化契合\nOutput: 客製化求職信草稿（3段式結構）+ 語調調整建議",
    input: "優化後履歷、目標公司資訊、JD 全文",
    process: "生成客製化求職信，突顯匹配度並展現文化契合",
    output: "客製化求職信草稿（3段式結構）+ 語調調整建議",
    synergy: ["2.01", "2.02", "2.03"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-10-20",
  },
  {
    id: "2.03",
    category: "職涯",
    name: "面試模擬教練",
    description:
      "Input: 目標職位、公司背景、個人經歷摘要\nProcess: 模擬行為面試 + 技術問題，提供即時回饋與 STAR 框架指導\nOutput: 模擬面試記錄 + 弱點分析 + 改善建議",
    input: "目標職位、公司背景、個人經歷摘要",
    process: "模擬行為面試 + 技術問題，提供即時回饋與 STAR 框架指導",
    output: "模擬面試記錄 + 弱點分析 + 改善建議",
    synergy: ["2.01", "2.02", "2.03"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    link: "https://chatgpt.com/g/g-example-203",
    updatedAt: "2025-10-25",
  },
  {
    id: "2.04",
    category: "職涯",
    name: "職涯路徑規劃師",
    description:
      "Input: 目前職位、技能盤點、3–5年目標\nProcess: 分析技能缺口，生成職涯路徑地圖與里程碑計畫\nOutput: 職涯路徑圖 + 技能提升計畫 + 每季行動清單",
    input: "目前職位、技能盤點、3–5年目標",
    process: "分析技能缺口，生成職涯路徑地圖與里程碑計畫",
    output: "職涯路徑圖 + 技能提升計畫 + 每季行動清單",
    synergy: ["2.04", "2.05"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-11-01",
  },
  {
    id: "2.05",
    category: "職涯",
    name: "LinkedIn個人品牌優化",
    description:
      "Input: LinkedIn 現有個人檔案、目標職位、個人價值主張\nProcess: 優化標題、摘要、工作描述，強化個人品牌敘事\nOutput: 優化後各欄位文案 + 個人品牌敘事框架",
    input: "LinkedIn 現有個人檔案、目標職位、個人價值主張",
    process: "優化標題、摘要、工作描述，強化個人品牌敘事",
    output: "優化後各欄位文案 + 個人品牌敘事框架",
    synergy: ["2.04", "2.05"],
    platform: "gpt",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-11-05",
  },
  {
    id: "2.06",
    category: "職涯",
    name: "薪資談判策略師",
    description:
      "Input: 目標薪資範圍、市場薪資數據、目前 offer 條件\nProcess: 生成談判腳本，分析籌碼，提供話術與反制準備\nOutput: 談判策略報告 + 場景話術 + 最佳情境/底線設定",
    input: "目標薪資範圍、市場薪資數據、目前 offer 條件",
    process: "生成談判腳本，分析籌碼，提供話術與反制準備",
    output: "談判策略報告 + 場景話術 + 最佳情境/底線設定",
    synergy: ["2.06"],
    platform: "claude",
    status: "WIP",
    author: "Peter",
    updatedAt: "2025-12-01",
  },

  // 流程 — Process
  {
    id: "3.01",
    category: "流程",
    name: "SOP 生成器",
    description:
      "Input: 流程名稱、步驟描述（口語版）、執行角色\nProcess: 將口語描述轉化為標準化 SOP，含決策點與異常處理\nOutput: 結構化 SOP 文件（Markdown）+ 流程圖文字描述",
    input: "流程名稱、步驟描述（口語版）、執行角色",
    process: "將口語描述轉化為標準化 SOP，含決策點與異常處理",
    output: "結構化 SOP 文件（Markdown）+ 流程圖文字描述",
    synergy: ["3.01", "3.02"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    link: "https://claude.ai/project/example-301",
    updatedAt: "2025-10-01",
  },
  {
    id: "3.02",
    category: "流程",
    name: "流程優化分析師",
    description:
      "Input: 現有 SOP、瓶頸描述、KPI 目標\nProcess: 識別冗餘步驟、等待時間與自動化機會，提出優化方案\nOutput: 優化建議報告 + 改善前後對比 + 自動化可行性評估",
    input: "現有 SOP、瓶頸描述、KPI 目標",
    process: "識別冗餘步驟、等待時間與自動化機會，提出優化方案",
    output: "優化建議報告 + 改善前後對比 + 自動化可行性評估",
    synergy: ["3.01", "3.02"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-10-05",
  },
  {
    id: "3.03",
    category: "流程",
    name: "會議紀錄助理",
    description:
      "Input: 會議錄音逐字稿或筆記、參與者名單\nProcess: 提取決議事項、行動項目、負責人，整理結構化摘要\nOutput: 會議紀錄（摘要+決議+行動清單）+ Follow-up 郵件草稿",
    input: "會議錄音逐字稿或筆記、參與者名單",
    process: "提取決議事項、行動項目、負責人，整理結構化摘要",
    output: "會議紀錄（摘要+決議+行動清單）+ Follow-up 郵件草稿",
    synergy: ["3.03"],
    platform: "gemini",
    status: "Done",
    author: "Amy",
    link: "https://gemini.google.com/gems/example-303",
    updatedAt: "2025-10-10",
  },
  {
    id: "3.04",
    category: "流程",
    name: "自動化可行性評估師",
    description:
      "Input: 流程描述、工具現況（使用中系統）、ROI 期望\nProcess: 套用 Digital Readiness Scorecard，評估自動化成熟度與優先順序\nOutput: 可行性評分報告 + 推薦工具組合 + 實施路線圖",
    input: "流程描述、工具現況（使用中系統）、ROI 期望",
    process: "套用 Digital Readiness Scorecard，評估自動化成熟度與優先順序",
    output: "可行性評分報告 + 推薦工具組合 + 實施路線圖",
    synergy: ["3.02", "3.04"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-10-15",
  },
  {
    id: "3.05",
    category: "流程",
    name: "SIPOC 框架生成器",
    description:
      "Input: 核心業務流程名稱、產品/服務類型\nProcess: 引導式問答生成 SIPOC 表格（供應商/輸入/流程/輸出/客戶）\nOutput: 完整 SIPOC 圖表 + 關鍵指標建議",
    input: "核心業務流程名稱、產品/服務類型",
    process: "引導式問答生成 SIPOC 表格（供應商/輸入/流程/輸出/客戶）",
    output: "完整 SIPOC 圖表 + 關鍵指標建議",
    synergy: ["3.05"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-10-20",
  },

  // 專案 — Project
  {
    id: "4.01",
    category: "專案",
    name: "專案章程生成器",
    description:
      "Input: 專案名稱、目標描述、主要利害關係人、預算範圍\nProcess: 生成標準化專案章程，定義範疇、里程碑、風險與成功標準\nOutput: 完整專案章程文件 + 利害關係人地圖",
    input: "專案名稱、目標描述、主要利害關係人、預算範圍",
    process: "生成標準化專案章程，定義範疇、里程碑、風險與成功標準",
    output: "完整專案章程文件 + 利害關係人地圖",
    synergy: ["4.01", "4.02"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    link: "https://claude.ai/project/example-401",
    updatedAt: "2025-09-15",
  },
  {
    id: "4.02",
    category: "專案",
    name: "WBS 任務分解助理",
    description:
      "Input: 專案章程、主要交付物清單\nProcess: 遞迴分解工作包至可執行任務層，估算工時與依賴關係\nOutput: 多層 WBS 結構 + 甘特圖文字版 + 資源需求清單",
    input: "專案章程、主要交付物清單",
    process: "遞迴分解工作包至可執行任務層，估算工時與依賴關係",
    output: "多層 WBS 結構 + 甘特圖文字版 + 資源需求清單",
    synergy: ["4.01", "4.02"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-09-20",
  },
  {
    id: "4.03",
    category: "專案",
    name: "風險登記簿助理",
    description:
      "Input: 專案類型、已知風險描述、里程碑計畫\nProcess: 識別潛在風險，評估機率與影響，生成應對策略\nOutput: 風險登記簿（含優先矩陣）+ 應對計畫摘要",
    input: "專案類型、已知風險描述、里程碑計畫",
    process: "識別潛在風險，評估機率與影響，生成應對策略",
    output: "風險登記簿（含優先矩陣）+ 應對計畫摘要",
    synergy: ["4.03"],
    platform: "claude",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-09-25",
  },
  {
    id: "4.04",
    category: "專案",
    name: "每週進度報告生成器",
    description:
      "Input: 本週完成事項、下週計畫、阻礙因素、KPI 數據\nProcess: 結構化生成進度報告，突顯風險與決策需求\nOutput: 週報草稿（執行摘要+細節+行動項）+ 主管摘要版",
    input: "本週完成事項、下週計畫、阻礙因素、KPI 數據",
    process: "結構化生成進度報告，突顯風險與決策需求",
    output: "週報草稿（執行摘要+細節+行動項）+ 主管摘要版",
    synergy: ["4.04"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-10-01",
  },
  {
    id: "4.05",
    category: "專案",
    name: "利害關係人溝通規劃師",
    description:
      "Input: 利害關係人清單、權力/利益分析、溝通目標\nProcess: 設計客製化溝通計畫，包含頻率、管道與訊息框架\nOutput: 溝通計畫矩陣 + 關鍵訊息模板",
    input: "利害關係人清單、權力/利益分析、溝通目標",
    process: "設計客製化溝通計畫，包含頻率、管道與訊息框架",
    output: "溝通計畫矩陣 + 關鍵訊息模板",
    synergy: ["4.05"],
    platform: "claude",
    status: "WIP",
    author: "Peter",
    updatedAt: "2025-12-01",
  },

  // 招募 — Recruiting
  {
    id: "5.01",
    category: "招募",
    name: "職位描述撰寫助理",
    description:
      "Input: 職位名稱、主要職責、必備技能、公司文化關鍵字\nProcess: 生成吸引人才且符合 DEI 原則的 JD，平衡技術與文化要求\nOutput: 完整 JD 草稿（含必備/加分條件）+ 平台發布版本",
    input: "職位名稱、主要職責、必備技能、公司文化關鍵字",
    process: "生成吸引人才且符合 DEI 原則的 JD，平衡技術與文化要求",
    output: "完整 JD 草稿（含必備/加分條件）+ 平台發布版本",
    synergy: ["5.01", "5.02", "5.03"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    link: "https://chatgpt.com/g/g-example-501",
    updatedAt: "2025-09-01",
  },
  {
    id: "5.02",
    category: "招募",
    name: "履歷篩選評分助理",
    description:
      "Input: JD 全文、候選人履歷（批次）、評分維度設定\nProcess: 依照評分標準逐一評估候選人，生成排序與推薦理由\nOutput: 候選人評分表 + 前三名推薦摘要 + 面試邀請草稿",
    input: "JD 全文、候選人履歷（批次）、評分維度設定",
    process: "依照評分標準逐一評估候選人，生成排序與推薦理由",
    output: "候選人評分表 + 前三名推薦摘要 + 面試邀請草稿",
    synergy: ["5.01", "5.02", "5.03"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-09-10",
  },
  {
    id: "5.03",
    category: "招募",
    name: "面試問題設計師",
    description:
      "Input: 職位 JD、核心能力模型、面試階段（初/中/終）\nProcess: 生成結構化面試問題組，涵蓋行為/情境/技術面向\nOutput: 面試問題庫（含評分標準）+ 面試官指引",
    input: "職位 JD、核心能力模型、面試階段（初/中/終）",
    process: "生成結構化面試問題組，涵蓋行為/情境/技術面向",
    output: "面試問題庫（含評分標準）+ 面試官指引",
    synergy: ["5.01", "5.02", "5.03"],
    platform: "gpt",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-09-15",
  },
  {
    id: "5.04",
    category: "招募",
    name: "錄取 Offer 信撰寫助理",
    description:
      "Input: 候選人資訊、薪資條件、職位細節、入職日期\nProcess: 生成專業友善的 Offer 信，含條件摘要與下一步說明\nOutput: Offer 信草稿 + 內部核准用摘要",
    input: "候選人資訊、薪資條件、職位細節、入職日期",
    process: "生成專業友善的 Offer 信，含條件摘要與下一步說明",
    output: "Offer 信草稿 + 內部核准用摘要",
    synergy: ["5.04"],
    platform: "gpt",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-09-20",
  },
  {
    id: "5.05",
    category: "招募",
    name: "人才招募管道分析師",
    description:
      "Input: 歷史招募數據、各管道成本、轉換率\nProcess: 分析各招募管道 ROI，識別高效管道與改善機會\nOutput: 管道績效報告 + 預算重分配建議 + 季度招募策略",
    input: "歷史招募數據、各管道成本、轉換率",
    process: "分析各招募管道 ROI，識別高效管道與改善機會",
    output: "管道績效報告 + 預算重分配建議 + 季度招募策略",
    synergy: ["5.05"],
    platform: "gemini",
    status: "Not started",
    author: "Peter",
    updatedAt: "2025-12-15",
  },

  // 顧問 — Consulting
  {
    id: "6.01",
    category: "顧問",
    name: "客戶需求訪談助理",
    description:
      "Input: 客戶行業、初步問題描述、訪談目標\nProcess: 生成結構化訪談問題，含探針問題與假設驗證問題\nOutput: 訪談問題指引 + 記錄模板 + 洞察整理框架",
    input: "客戶行業、初步問題描述、訪談目標",
    process: "生成結構化訪談問題，含探針問題與假設驗證問題",
    output: "訪談問題指引 + 記錄模板 + 洞察整理框架",
    synergy: ["6.01", "6.02"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    link: "https://claude.ai/project/example-601",
    updatedAt: "2025-08-20",
  },
  {
    id: "6.02",
    category: "顧問",
    name: "問題定義框架師",
    description:
      "Input: 訪談洞察、客戶症狀描述、業務背景\nProcess: 套用 5-Why / Problem Tree / Issue Tree 框架定義根本原因\nOutput: 問題定義報告 + 假設清單 + 分析優先順序",
    input: "訪談洞察、客戶症狀描述、業務背景",
    process: "套用 5-Why / Problem Tree / Issue Tree 框架定義根本原因",
    output: "問題定義報告 + 假設清單 + 分析優先順序",
    synergy: ["6.01", "6.02"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-08-25",
  },
  {
    id: "6.03",
    category: "顧問",
    name: "提案簡報架構師",
    description:
      "Input: 問題定義、解決方案草稿、客戶偏好風格\nProcess: 生成麥肯錫金字塔原則提案架構，含故事線與說服邏輯\nOutput: 提案大綱（含每頁核心訊息）+ 簡報結構建議",
    input: "問題定義、解決方案草稿、客戶偏好風格",
    process: "生成麥肯錫金字塔原則提案架構，含故事線與說服邏輯",
    output: "提案大綱（含每頁核心訊息）+ 簡報結構建議",
    synergy: ["6.03", "6.04"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-09-01",
  },
  {
    id: "6.04",
    category: "顧問",
    name: "顧問報告生成器",
    description:
      "Input: 分析數據、關鍵發現、建議行動\nProcess: 生成結構化顧問報告，含執行摘要、分析詳情、實施建議\nOutput: 完整顧問報告草稿（Word格式）+ 執行摘要一頁版",
    input: "分析數據、關鍵發現、建議行動",
    process: "生成結構化顧問報告，含執行摘要、分析詳情、實施建議",
    output: "完整顧問報告草稿（Word格式）+ 執行摘要一頁版",
    synergy: ["6.03", "6.04"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-09-05",
  },
  {
    id: "6.05",
    category: "顧問",
    name: "ROI 計算模型助理",
    description:
      "Input: 投資項目描述、成本明細、預期效益指標\nProcess: 構建 ROI 計算模型，敏感性分析，生成商業論證\nOutput: ROI 計算表 + 情境分析 + 商業論證摘要",
    input: "投資項目描述、成本明細、預期效益指標",
    process: "構建 ROI 計算模型，敏感性分析，生成商業論證",
    output: "ROI 計算表 + 情境分析 + 商業論證摘要",
    synergy: ["6.05"],
    platform: "gemini",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-09-10",
  },
  {
    id: "6.06",
    category: "顧問",
    name: "客戶後續追蹤郵件助理",
    description:
      "Input: 會議/提案記錄、客戶關係階段、下一步行動\nProcess: 生成個性化追蹤郵件，強化關係並推進銷售漏斗\nOutput: 追蹤郵件草稿 + 後續跟進計畫",
    input: "會議/提案記錄、客戶關係階段、下一步行動",
    process: "生成個性化追蹤郵件，強化關係並推進銷售漏斗",
    output: "追蹤郵件草稿 + 後續跟進計畫",
    synergy: ["6.06"],
    platform: "gpt",
    status: "Pause",
    author: "Amy",
    updatedAt: "2025-11-01",
  },

  // 策略 — Strategy
  {
    id: "7.01",
    category: "策略",
    name: "SWOT 分析助理",
    description:
      "Input: 公司/產品名稱、行業背景、主要競爭對手\nProcess: 系統化生成 SWOT 矩陣，並從優勢出發推導策略方向\nOutput: SWOT 分析矩陣 + SO/WO/ST/WT 策略建議",
    input: "公司/產品名稱、行業背景、主要競爭對手",
    process: "系統化生成 SWOT 矩陣，並從優勢出發推導策略方向",
    output: "SWOT 分析矩陣 + SO/WO/ST/WT 策略建議",
    synergy: ["7.01", "7.02"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    link: "https://chatgpt.com/g/g-example-701",
    updatedAt: "2025-08-01",
  },
  {
    id: "7.02",
    category: "策略",
    name: "競爭定位策略師",
    description:
      "Input: SWOT 分析結果、市場區隔數據、價值主張草稿\nProcess: 套用波特五力 + 定位圖，識別差異化空間與藍海機會\nOutput: 競爭定位地圖 + 差異化策略建議 + 訊息框架",
    input: "SWOT 分析結果、市場區隔數據、價值主張草稿",
    process: "套用波特五力 + 定位圖，識別差異化空間與藍海機會",
    output: "競爭定位地圖 + 差異化策略建議 + 訊息框架",
    synergy: ["7.01", "7.02"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-08-10",
  },
  {
    id: "7.03",
    category: "策略",
    name: "OKR 設計師",
    description:
      "Input: 年度/季度策略方向、部門目標、現有 KPI\nProcess: 將策略方向轉化為 OKR 框架，確保對齊性與可衡量性\nOutput: OKR 草稿（O + 3–5 KR）+ 追蹤機制建議",
    input: "年度/季度策略方向、部門目標、現有 KPI",
    process: "將策略方向轉化為 OKR 框架，確保對齊性與可衡量性",
    output: "OKR 草稿（O + 3–5 KR）+ 追蹤機制建議",
    synergy: ["7.03", "7.04"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-08-15",
  },
  {
    id: "7.04",
    category: "策略",
    name: "策略執行路線圖",
    description:
      "Input: OKR / 策略目標、資源限制、時間範圍\nProcess: 將策略拆解為季度計畫，識別關鍵里程碑與依賴關係\nOutput: 12個月執行路線圖 + 季度優先事項 + 資源需求矩陣",
    input: "OKR / 策略目標、資源限制、時間範圍",
    process: "將策略拆解為季度計畫，識別關鍵里程碑與依賴關係",
    output: "12個月執行路線圖 + 季度優先事項 + 資源需求矩陣",
    synergy: ["7.03", "7.04"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-08-20",
  },
  {
    id: "7.05",
    category: "策略",
    name: "市場進入策略師",
    description:
      "Input: 目標市場描述、產品/服務定位、資源規模\nProcess: 分析市場進入模式（直接/合作/授權），評估風險與機會\nOutput: 市場進入策略報告 + 先導計畫建議 + Go/No-Go 框架",
    input: "目標市場描述、產品/服務定位、資源規模",
    process: "分析市場進入模式（直接/合作/授權），評估風險與機會",
    output: "市場進入策略報告 + 先導計畫建議 + Go/No-Go 框架",
    synergy: ["7.05"],
    platform: "gemini",
    status: "WIP",
    author: "Peter",
    updatedAt: "2025-12-10",
  },
  {
    id: "7.06",
    category: "策略",
    name: "商業模式畫布助理",
    description:
      "Input: 業務描述、目標客群、核心價值主張\nProcess: 填充9個 BMC 模塊，識別商業模式假設與驗證優先順序\nOutput: 完整商業模式畫布 + 假設優先清單 + MVP 建議",
    input: "業務描述、目標客群、核心價值主張",
    process: "填充9個 BMC 模塊，識別商業模式假設與驗證優先順序",
    output: "完整商業模式畫布 + 假設優先清單 + MVP 建議",
    synergy: ["7.06"],
    platform: "gpt",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-09-01",
  },

  // Additional skills to reach ~40 total
  {
    id: "1.09",
    category: "內容行銷",
    name: "關鍵字研究助理",
    description:
      "Input: 核心主題、目標市場、競品網域\nProcess: 擴展語意群集，識別低競爭高價值長尾詞，優先化機會\nOutput: 關鍵字列表（含搜尋量/競爭度估計）+ 內容主題建議",
    input: "核心主題、目標市場、競品網域",
    process: "擴展語意群集，識別低競爭高價值長尾詞，優先化機會",
    output: "關鍵字列表（含搜尋量/競爭度估計）+ 內容主題建議",
    synergy: ["1.03", "1.09"],
    platform: "gemini",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-11-25",
  },
  {
    id: "3.06",
    category: "流程",
    name: "工作交接文件生成器",
    description:
      "Input: 離職/轉調人員姓名、負責業務清單、交接期限\nProcess: 結構化整理交接文件，包含背景、狀態、聯絡人、注意事項\nOutput: 完整交接文件 + 新負責人 Onboarding 清單",
    input: "離職/轉調人員姓名、負責業務清單、交接期限",
    process: "結構化整理交接文件，包含背景、狀態、聯絡人、注意事項",
    output: "完整交接文件 + 新負責人 Onboarding 清單",
    synergy: ["3.06"],
    platform: "claude",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-10-25",
  },
  {
    id: "4.06",
    category: "專案",
    name: "回顧會議引導助理",
    description:
      "Input: 專案結果摘要、團隊規模、回顧聚焦主題\nProcess: 設計結構化回顧工作坊流程（Start/Stop/Continue），引導洞察\nOutput: 回顧會議議程 + 問題引導卡 + 行動改善清單模板",
    input: "專案結果摘要、團隊規模、回顧聚焦主題",
    process: "設計結構化回顧工作坊流程（Start/Stop/Continue），引導洞察",
    output: "回顧會議議程 + 問題引導卡 + 行動改善清單模板",
    synergy: ["4.06"],
    platform: "gpt",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-10-05",
  },
  {
    id: "5.06",
    category: "招募",
    name: "員工入職計畫生成器",
    description:
      "Input: 職位類型、部門、入職日期、導師指定\nProcess: 生成結構化 30-60-90 天入職計畫，含學習目標與里程碑\nOutput: 入職計畫文件 + 每週 Checklist + 導師指引",
    input: "職位類型、部門、入職日期、導師指定",
    process: "生成結構化 30-60-90 天入職計畫，含學習目標與里程碑",
    output: "入職計畫文件 + 每週 Checklist + 導師指引",
    synergy: ["5.06"],
    platform: "gpt",
    status: "Done",
    author: "Amy",
    updatedAt: "2025-09-25",
  },
  {
    id: "6.07",
    category: "顧問",
    name: "工作坊設計助理",
    description:
      "Input: 工作坊主題、參與人數、時長、目標產出\nProcess: 設計引導式工作坊流程，含破冰、分組討論、收斂決策活動\nOutput: 工作坊議程 + 引導腳本 + 物料清單",
    input: "工作坊主題、參與人數、時長、目標產出",
    process: "設計引導式工作坊流程，含破冰、分組討論、收斂決策活動",
    output: "工作坊議程 + 引導腳本 + 物料清單",
    synergy: ["6.07"],
    platform: "claude",
    status: "Done",
    author: "Peter",
    updatedAt: "2025-09-15",
  },
];
