import { Skill } from "./skills";

export const skills: Skill[] = [

  // ── 營運 / search-index ──────────────────────────────────────────────────
  {
    id: "0.01",
    category: "營運",
    project: "search-index",
    name: "行政助理 ─ 搜尋助理索引",
    description:
      "Input: A user inquiry describing a task or need to be solved.\n\nProcess: Interpret the intent, match it against a structured assistant index using functional descriptions, filter to usable entries, and decide whether to recommend or ask one clarification.\n\nOutput: A concise recommendation of the most relevant assistant(s), or a clear request for clarification / inability to recommend.",
    input: "A user inquiry describing a task or need to be solved.",
    process:
      "Interpret the intent, match it against a structured assistant index using functional descriptions, filter to usable entries, and decide whether to recommend or ask one clarification.",
    output:
      "A concise recommendation of the most relevant assistant(s), or a clear request for clarification / inability to recommend.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "1/21",
  },

  // ── 品牌行銷 / writing-assistant ────────────────────────────────────────
  {
    id: "1.01",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 靈感發想",
    description:
      "Input: The user provides an abstract philosophical question and answers assistant's prompts.\n\nProcess: Use single-step Socratic questions, give a score and brief comment, add a short parable if shallow, and guide through ~5 rounds toward clarity.\n\nOutput: A score, commentary, optional parable, and the next, more focused philosophical question.",
    input: "The user provides an abstract philosophical question and answers assistant's prompts.",
    process: "Use single-step Socratic questions, give a score and brief comment, add a short parable if shallow, and guide through ~5 rounds toward clarity.",
    output: "A score, commentary, optional parable, and the next, more focused philosophical question.",
    synergy: ["1.01", "1.02", "1.03", "1.04", "1.05", "1.06"],
    platform: "claude",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "8/13",
    installCommand: `curl -sL https://zynkr.ai/s/1.01.md -o ~/.claude/skills/writing-ideation.md`,
  },
  {
    id: "1.02",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 文章風格導航員",
    description:
      "Input: User gives article draft (topic + core ideas); templates and style guide are preloaded.\n\nProcess: Multi-turn - propose 3 outlines, 3 key points per section, then write paragraphs stepwise with user review, following the style guide.\n\nOutput: Clear outline, section bullet lists, and a 1000–1200-word article drafted in the user's style.",
    input: "User gives article draft (topic + core ideas); templates and style guide are preloaded.",
    process: "Multi-turn - propose 3 outlines, 3 key points per section, then write paragraphs stepwise with user review, following the style guide.",
    output: "Clear outline, section bullet lists, and a 1000–1200-word article drafted in the user's style.",
    synergy: ["1.01", "1.02", "1.03", "1.04", "1.05", "1.06"],
    platform: "claude",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "8/13",
    installCommand: `curl -sL https://zynkr.ai/s/1.02.md -o ~/.claude/skills/writing-style.md`,
  },
  {
    id: "1.03",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 編輯助手",
    description:
      "Input: User provides an article draft; a Style Guide exists in the knowledge base.\n\nProcess: Check presence of article, verify relevance to Style Guide, then list edit suggestions: original text, proposed revision, and reason. Ensure mobile-friendly style, avoid \"不是⋯而是⋯\", and confirm choices with the user.\n\nOutput: A numbered list of edit suggestions and a question asking which to adopt.",
    input: "User provides an article draft; a Style Guide exists in the knowledge base.",
    process: "Check presence of article, verify relevance to Style Guide, then list edit suggestions: original text, proposed revision, and reason. Ensure mobile-friendly style, avoid \"不是⋯而是⋯\", and confirm choices with the user.",
    output: "A numbered list of edit suggestions and a question asking which to adopt.",
    synergy: ["1.01", "1.02", "1.03", "1.04", "1.05", "1.06"],
    platform: "claude",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "8/13",
    installCommand: `curl -sL https://zynkr.ai/s/1.03.md -o ~/.claude/skills/writing-editor.md`,
  },
  {
    id: "1.04",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 讀者審稿",
    description:
      "Input: User provides an article for critique; limited Memory (SEO + style prefs) may be used.\n\nProcess: Evaluate structure, persuasiveness, SEO, and readability; analyze flaws from a third-person, oppositional stance; give scores with reasons; list SEO keywords using allowed Memory; provide directional improvements without rewriting.\n\nOutput: Fixed-format: scoring table, opponent-style critique, SEO keyword list with rationale, and non-rewriting improvement suggestions.",
    input: "User provides an article for critique; limited Memory (SEO + style prefs) may be used.",
    process: "Evaluate structure, persuasiveness, SEO, and readability; analyze flaws from a third-person, oppositional stance; give scores with reasons; list SEO keywords using allowed Memory; provide directional improvements without rewriting.",
    output: "Fixed-format: scoring table, opponent-style critique, SEO keyword list with rationale, and non-rewriting improvement suggestions.",
    synergy: ["1.01", "1.02", "1.03", "1.04", "1.05", "1.06"],
    platform: "claude",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "8/13",
    installCommand: `curl -sL https://zynkr.ai/s/1.04.md -o ~/.claude/skills/writing-reader.md`,
  },
  {
    id: "1.05",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 標題小幫手",
    description:
      "Input: User provides an article, topic, or file; limited Memory (SEO + style preferences) may be referenced.\n\nProcess: Generate either 10 SEO titles or a full SEO strategy. Use Taiwan search habits, five MECE topic categories, keyword groups, outlines, and optimization advice. Never invent memory or rewrite user content.\n\nOutput: SEO titles with reasons and MECE classification, or a complete SEO strategy with keywords, outline, and recommendations.",
    input: "User provides an article, topic, or file; limited Memory (SEO + style preferences) may be referenced.",
    process: "Generate either 10 SEO titles or a full SEO strategy. Use Taiwan search habits, five MECE topic categories, keyword groups, outlines, and optimization advice. Never invent memory or rewrite user content.",
    output: "SEO titles with reasons and MECE classification, or a complete SEO strategy with keywords, outline, and recommendations.",
    synergy: ["1.01", "1.02", "1.03", "1.04", "1.05", "1.06"],
    platform: "claude",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "8/13",
    installCommand: `curl -sL https://zynkr.ai/s/1.05.md -o ~/.claude/skills/writing-title.md`,
  },
  {
    id: "1.06",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 客製化行動呼籲",
    description:
      "Input: An article draft provided by the author.\n\nProcess: Analyze the article's theme, audience, and conversion goal, then match it to approved CTA categories and templates defined in Zynkr's CTA handbook.\n\nOutput: Three ready-to-use CTA options with titles, copy, category, sub-goal, placement advice, and validated links.",
    input: "An article draft provided by the author.",
    process: "Analyze the article's theme, audience, and conversion goal, then match it to approved CTA categories and templates defined in Zynkr's CTA handbook.",
    output: "Three ready-to-use CTA options with titles, copy, category, sub-goal, placement advice, and validated links.",
    synergy: ["1.01", "1.02", "1.03", "1.04", "1.05", "1.06"],
    platform: "claude",
    status: "Done",
    author: "Raina Li",
    updatedAt: "1/5",
    installCommand: `curl -sL https://zynkr.ai/s/1.06.md -o ~/.claude/skills/writing-cta.md`,
  },
  {
    id: "1.07",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 內容標籤助理",
    description: "根據文章內容選擇適合上哪些標籤",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "",
  },
  {
    id: "1.08",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 文章裂變",
    description:
      "Input: A full or partial article text, optionally with a writing or critique goal.\n\nProcess: Analyze structure and ideas, extract an outline and summary, reflect through guided questions, then synthesize refined insights.\n\nOutput: Clear outlines, summaries, virality analysis, reflective dialogue, and a new actionable outline.",
    input: "A full or partial article text, optionally with a writing or critique goal.",
    process: "Analyze structure and ideas, extract an outline and summary, reflect through guided questions, then synthesize refined insights.",
    output: "Clear outlines, summaries, virality analysis, reflective dialogue, and a new actionable outline.",
    synergy: ["1.08", "1.02", "1.03", "1.04", "1.05", "1.06"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "10/23",
  },
  {
    id: "1.09",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ 翻譯蒟蒻",
    description:
      "Input: User provides text in English or another language.\n\nProcess: I translate it into natural, conversational Traditional Chinese using Taiwanese expressions and tone.\n\nOutput: Fluent, localized Traditional Chinese (Taiwan) text that sounds like everyday spoken or written language.",
    input: "User provides text in English or another language.",
    process: "I translate it into natural, conversational Traditional Chinese using Taiwanese expressions and tone.",
    output: "Fluent, localized Traditional Chinese (Taiwan) text that sounds like everyday spoken or written language.",
    synergy: [],
    platform: "multi",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "5/2",
  },
  {
    id: "1.10",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ AI 素養文章選題",
    description:
      "Input: Unstructured user context (intent, knowledge, audience, workflow) plus two reference documents: AI rules (K1) and role distribution (K2).\n\nProcess: Validate context → select target role → generate role-specific workplace problems using a strict 3-stage IPO pipeline.\n\nOutput: Clear validation result, ranked role options, and 3 realistic workplace problems for AI learning use cases.",
    input: "Unstructured user context (intent, knowledge, audience, workflow) plus two reference documents: AI rules (K1) and role distribution (K2).",
    process: "Validate context → select target role → generate role-specific workplace problems using a strict 3-stage IPO pipeline.",
    output: "Clear validation result, ranked role options, and 3 realistic workplace problems for AI learning use cases.",
    synergy: ["1.10", "1.11"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "10/24",
  },
  {
    id: "1.11",
    category: "品牌行銷",
    project: "writing-assistant",
    name: "寫作助理 ─ AI 素養文章撰寫",
    description:
      "Input: A prepared context packet describing audience, pain point, constraints, and desired outcome.\n\nProcess: Diagnose intent and cognition, reframe the problem, then craft a first-person, action-driven article using a pattern-break → reframe → copy-paste approach.\n\nOutput: A ready-to-publish AI productivity article with immediate, reusable prompts.",
    input: "A prepared context packet describing audience, pain point, constraints, and desired outcome.",
    process: "Diagnose intent and cognition, reframe the problem, then craft a first-person, action-driven article using a pattern-break → reframe → copy-paste approach.",
    output: "A ready-to-publish AI productivity article with immediate, reusable prompts.",
    synergy: ["1.10", "1.11"],
    platform: "gpt",
    status: "Done",
    author: "Bicky Yang",
    updatedAt: "12/30",
  },

  // ── 品牌行銷 / brand-marketing-assistant ────────────────────────────────
  {
    id: "1.12",
    category: "品牌行銷",
    project: "brand-marketing-assistant",
    name: "品牌行銷助理 ─ 設計品牌行銷故事線",
    description: "幫忙順品牌行銷的故事線和檢查邏輯",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "",
  },
  {
    id: "1.13",
    category: "品牌行銷",
    project: "brand-marketing-assistant",
    name: "品牌行銷助理 ─ 分頁設定",
    description: "根據基底內容分頁品牌行銷",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "",
  },
  {
    id: "1.14",
    category: "品牌行銷",
    project: "brand-marketing-assistant",
    name: "品牌行銷助理 ─ 品牌行銷視覺呈現選擇",
    description: "根據內容和分頁規格選擇視覺呈現",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "",
  },

  // ── 人才發展 / resume ────────────────────────────────────────────────────
  {
    id: "2.01",
    category: "人才發展",
    project: "resume",
    name: "履歷客製化 ─ 分析職缺",
    description:
      "Input: Job description or application link (or minimal role/company details).\n\nProcess: Decode hiring intent, role context, priorities, success metrics, and ATS filters using structured analysis (MECE, 80/20).\n\nOutput: Clear role summary, prioritized skills, success KPIs, and ATS-ready keywords for CV tailoring and interview prep.",
    input: "Job description or application link (or minimal role/company details).",
    process: "Decode hiring intent, role context, priorities, success metrics, and ATS filters using structured analysis (MECE, 80/20).",
    output: "Clear role summary, prioritized skills, success KPIs, and ATS-ready keywords for CV tailoring and interview prep.",
    synergy: ["2.01", "2.02", "2.03", "2.04", "2.05"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "6/5",
  },
  {
    id: "2.02",
    category: "人才發展",
    project: "resume",
    name: "履歷客製化 ─ 找到價值主張",
    description:
      "Input: User's CV, target job requirements, and past experience descriptions.\n\nProcess: Identify skill gaps, guide structured SCQA storytelling, probe for clarity, and refine impact-focused narratives.\n\nOutput: Clear, job-aligned skill stories ready for CV bullets, interviews, or fit assessment.",
    input: "User's CV, target job requirements, and past experience descriptions.",
    process: "Identify skill gaps, guide structured SCQA storytelling, probe for clarity, and refine impact-focused narratives.",
    output: "Clear, job-aligned skill stories ready for CV bullets, interviews, or fit assessment.",
    synergy: ["2.01", "2.02", "2.03", "2.04", "2.05"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "9/28",
  },
  {
    id: "2.03",
    category: "人才發展",
    project: "resume",
    name: "履歷客製化 ─ 評分並分析優劣",
    description:
      "Input: Candidate CV plus target role context and prior discussion insights.\n\nProcess: Score fit across relevance, value, narrative, and ATS; benchmark against top peers; identify gaps; coach improvements step-by-step.\n\nOutput: Clear fit scores, competitive benchmarking, and actionable recommendations to optimize the CV and career positioning.",
    input: "Candidate CV plus target role context and prior discussion insights.",
    process: "Score fit across relevance, value, narrative, and ATS; benchmark against top peers; identify gaps; coach improvements step-by-step.",
    output: "Clear fit scores, competitive benchmarking, and actionable recommendations to optimize the CV and career positioning.",
    synergy: ["2.01", "2.02", "2.03", "2.04", "2.05"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "9/28",
  },
  {
    id: "2.04",
    category: "人才發展",
    project: "resume",
    name: "履歷客製化 ─ 打造成長曲線",
    description:
      "Input: User's resume content and prior contextual analysis from earlier phases.\n\nProcess: Automatically analyze skill placement, depth, progression, and leadership signals across roles to assess career growth credibility.\n\nOutput: A structured diagnosis of progression quality, flagged risks, and concrete rewrite recommendations to strengthen the growth narrative.",
    input: "User's resume content and prior contextual analysis from earlier phases.",
    process: "Automatically analyze skill placement, depth, progression, and leadership signals across roles to assess career growth credibility.",
    output: "A structured diagnosis of progression quality, flagged risks, and concrete rewrite recommendations to strengthen the growth narrative.",
    synergy: ["2.01", "2.02", "2.03", "2.04", "2.05"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "9/28",
  },
  {
    id: "2.05",
    category: "人才發展",
    project: "resume",
    name: "履歷客製化 ─ 履歷撰寫",
    description:
      "Input: Existing resume content, prior optimization insights, and a fixed CV template.\n\nProcess: Rewrite and structure content to match the template using active, impact-driven language optimized for ATS and recruiters.\n\nOutput: A polished, job-ready resume with clear sections, quantified achievements, and acceptance checkpoints.",
    input: "Existing resume content, prior optimization insights, and a fixed CV template.",
    process: "Rewrite and structure content to match the template using active, impact-driven language optimized for ATS and recruiters.",
    output: "A polished, job-ready resume with clear sections, quantified achievements, and acceptance checkpoints.",
    synergy: ["2.01", "2.02", "2.03", "2.04", "2.05"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "9/28",
  },

  // ── 人才發展 / interview ─────────────────────────────────────────────────
  {
    id: "2.06",
    category: "人才發展",
    project: "interview",
    name: "面試猜題",
    description:
      "Input: Resume or key experiences, job description, interview stage, and company context (inferred if missing).\n\nProcess: Analyze the interview context from an interviewer's perspective and identify likely questions and evaluation signals.\n\nOutput: A concise interview question map with rationale, priority, and suggested questions for the recap Q&A.",
    input: "Resume or key experiences, job description, interview stage, and company context (inferred if missing).",
    process: "Analyze the interview context from an interviewer's perspective and identify likely questions and evaluation signals.",
    output: "A concise interview question map with rationale, priority, and suggested questions for the recap Q&A.",
    synergy: ["2.06", "2.07"],
    platform: "gpt",
    status: "Done",
    author: "Jane Liao",
  },
  {
    id: "2.07",
    category: "人才發展",
    project: "interview",
    name: "模擬面試",
    description:
      "Input: Resume, job description, interview stage, and company interview criteria or culture (if unavailable, inferred from public sources with disclosure).\n\nProcess: Analyze interview context, generate likely questions, and refine answers through structured, interviewer-perspective feedback.\n\nOutput: Clear, stage-ready interview answers with anticipated follow-ups and three tailored questions to ask the interviewer.",
    input: "Resume, job description, interview stage, and company interview criteria or culture (if unavailable, inferred from public sources with disclosure).",
    process: "Analyze interview context, generate likely questions, and refine answers through structured, interviewer-perspective feedback.",
    output: "Clear, stage-ready interview answers with anticipated follow-ups and three tailored questions to ask the interviewer.",
    synergy: ["2.06", "2.07"],
    platform: "gpt",
    status: "Done",
    author: "Jane Liao",
  },

  // ── 人才發展 / career-coach ──────────────────────────────────────────────
  {
    id: "2.08",
    category: "人才發展",
    project: "career-coach",
    name: "職涯教練",
    description: "",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },

  // ── 業務顧問 / career-consulting ────────────────────────────────────────
  {
    id: "2.09",
    category: "業務顧問",
    project: "career-consulting",
    name: "Career PrepPal｜職涯諮詢教練的資料分析助手",
    description: "PrepPal 職涯助手 是專為職涯諮詢教練設計的智慧資料分析工具。",
    synergy: [],
    platform: "gpt",
    status: "Pause",
    author: "Jane Liao",
    updatedAt: "8/21",
  },
  {
    id: "2.10",
    category: "業務顧問",
    project: "career-consulting",
    name: "CareerInsight Coach｜職涯洞察教練",
    description: "幫助教練快速形成諮詢藍圖，提升對話聚焦度，並確保 60 分鐘的諮詢環節產出最大化。",
    synergy: [],
    platform: "gpt",
    status: "Pause",
    author: "Jane Liao",
    updatedAt: "8/21",
  },

  // ── 業務顧問 / consulting-assistant ─────────────────────────────────────
  {
    id: "2.11",
    category: "業務顧問",
    project: "consulting-assistant",
    name: "顧問助理 ─ 痛點解析",
    description:
      "Input: User shares business context, team structure, challenges, and goals through guided Q&A.\n\nProcess: Conducts structured, step-by-step needs discovery by asking one question at a time, confirming understanding, and probing deeper.\n\nOutput: Clear, organized summary of user background, challenges, and needs, ready for strategic follow-up.",
    input: "User shares business context, team structure, challenges, and goals through guided Q&A.",
    process: "Conducts structured, step-by-step needs discovery by asking one question at a time, confirming understanding, and probing deeper.",
    output: "Clear, organized summary of user background, challenges, and needs, ready for strategic follow-up.",
    synergy: ["2.11", "2.12"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "7/9",
  },
  {
    id: "2.12",
    category: "業務顧問",
    project: "consulting-assistant",
    name: "顧問助理 ─ 公司未來願景描繪",
    description:
      "Input: Strategic context from founders or senior managers about vision, products, organization, and decision dynamics.\n\nProcess: Guided, structured conversation—one question at a time—to uncover long-term goals, value propositions, and operational realities.\n\nOutput: Concise strategic discovery summary to support downstream process mapping or pain point validation.",
    input: "Strategic context from founders or senior managers about vision, products, organization, and decision dynamics.",
    process: "Guided, structured conversation—one question at a time—to uncover long-term goals, value propositions, and operational realities.",
    output: "Concise strategic discovery summary to support downstream process mapping or pain point validation.",
    synergy: ["2.11", "2.12"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "7/18",
  },

  // ── 業務顧問 / operations-assistant ─────────────────────────────────────
  {
    id: "2.13",
    category: "業務顧問",
    project: "operations-assistant",
    name: "營運助理：流程探勘 (Virtual shadowing)",
    description: "",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },
  {
    id: "2.14",
    category: "業務顧問",
    project: "operations-assistant",
    name: "營運助理 ─ 流程探勘",
    description:
      "Input: A client's description of an inefficient or unclear business process.\n\nProcess: Guide structured questioning to map end-to-end steps, identify suppliers and customers, and infer standard inputs/outputs.\n\nOutput: A clear, reviewable process map presented as a structured table for improvement planning.",
    input: "A client's description of an inefficient or unclear business process.",
    process: "Guide structured questioning to map end-to-end steps, identify suppliers and customers, and infer standard inputs/outputs.",
    output: "A clear, reviewable process map presented as a structured table for improvement planning.",
    synergy: ["2.14", "2.15", "2.16"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "7/10",
  },
  {
    id: "2.15",
    category: "業務顧問",
    project: "operations-assistant",
    name: "營運助理 ─ 數位轉型評估",
    description:
      "Input: SIPOC-style process steps and contextual details (frequency, objectivity, decision rules).\n\nProcess: Diagnose automation suitability, assess ROI, classify tasks, and recommend appropriate technologies with concise rationale.\n\nOutput: A structured evaluation table, transformation recommendations, and a handoff prompt for solution design.",
    input: "SIPOC-style process steps and contextual details (frequency, objectivity, decision rules).",
    process: "Diagnose automation suitability, assess ROI, classify tasks, and recommend appropriate technologies with concise rationale.",
    output: "A structured evaluation table, transformation recommendations, and a handoff prompt for solution design.",
    synergy: ["2.14", "2.15", "2.16"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
  },
  {
    id: "2.16",
    category: "業務顧問",
    project: "operations-assistant",
    name: "營運經理 ─ 流程重構",
    description:
      "Input: Diagnosed process steps with automation readiness scores.\n\nProcess: Redesign each step into structured, automation-ready workflows with task breakdowns, system layer mapping, and tool suggestions.\n\nOutput: Builder-ready tables with sub-tasks, flow type, MVP stack, and a summary for digital transformation execution.",
    input: "Diagnosed process steps with automation readiness scores.",
    process: "Redesign each step into structured, automation-ready workflows with task breakdowns, system layer mapping, and tool suggestions.",
    output: "Builder-ready tables with sub-tasks, flow type, MVP stack, and a summary for digital transformation execution.",
    synergy: ["2.14", "2.15", "2.16"],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "7/20",
  },

  // ── 策略領導 / strategy-planning ────────────────────────────────────────
  {
    id: "3.01",
    category: "策略領導",
    project: "strategy-planning",
    name: "策略規劃",
    description: "幫忙策略規劃和設計解決方法",
    synergy: [],
    platform: "gpt",
    status: "WIP",
    author: "Peter Tu",
  },

  // ── 營運 / project-management ────────────────────────────────────────────
  {
    id: "3.02",
    category: "營運",
    project: "project-management",
    name: "專案管理發想 (Old)",
    description: "發想專案章程 One pager",
    synergy: [],
    platform: "gpt",
    status: "Out dated",
    author: "Peter Tu",
    updatedAt: "6/3",
  },
  {
    id: "3.03",
    category: "營運",
    project: "project-management",
    name: "專案章程發想 (New)",
    description:
      "Input: A proposed project, initiative, or problem the user wants to validate before execution.\n\nProcess: Structured, Socratic facilitation that stress-tests logic across purpose, problem, execution, governance, timing, metrics, and risks.\n\nOutput: A clarified, execution-ready project foundation with aligned rationale, plan, roles, timeline, success measures, and risk mitigation.",
    input: "A proposed project, initiative, or problem the user wants to validate before execution.",
    process: "Structured, Socratic facilitation that stress-tests logic across purpose, problem, execution, governance, timing, metrics, and risks.",
    output: "A clarified, execution-ready project foundation with aligned rationale, plan, roles, timeline, success measures, and risk mitigation.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "6/23",
  },
  {
    id: "3.04",
    category: "營運",
    project: "project-management",
    name: "專案規劃助理",
    description: "根據發想的專案列出一系列的執行項目",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },
  {
    id: "3.05",
    category: "營運",
    project: "project-management",
    name: "利害關係人提問模擬",
    description: "",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },

  // ── 營運 / project-assistant ─────────────────────────────────────────────
  {
    id: "3.06",
    category: "營運",
    project: "project-assistant",
    name: "專案助理 ─ 整理會議筆記",
    description:
      "Input: Raw meeting notes, transcripts, or unstructured updates.\n\nProcess: Reorganize scattered details into logical categories, inferring context while maintaining professional clarity.\n\nOutput: A structured \"Weekly Project Update\" featuring Summary, Progress, Blockers, and What's Next.",
    input: "Raw meeting notes, transcripts, or unstructured updates.",
    process: "Reorganize scattered details into logical categories, inferring context while maintaining professional clarity.",
    output: "A structured \"Weekly Project Update\" featuring Summary, Progress, Blockers, and What's Next.",
    synergy: [],
    platform: "multi",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "11/28",
  },
  {
    id: "3.07",
    category: "營運",
    project: "project-assistant",
    name: "專案追蹤助理",
    description:
      "Input: Bi-weekly meeting document with weekly summaries and sectioned updates.\n\nProcess: Identify latest and previous weeks, compare changes, detect additions/updates/deletions, surface risks and remaining actions, then structure notes per team.\n\nOutput: Concise Chinese meeting notes by team, each with Progress, Callouts/Risks, and Action Items, bullets under 20 characters.",
    input: "Bi-weekly meeting document with weekly summaries and sectioned updates.",
    process: "Identify latest and previous weeks, compare changes, detect additions/updates/deletions, surface risks and remaining actions, then structure notes per team.",
    output: "Concise Chinese meeting notes by team, each with Progress, Callouts/Risks, and Action Items, bullets under 20 characters.",
    synergy: [],
    platform: "gpt",
    status: "Pause",
    author: "Peter Tu",
    updatedAt: "11/20",
  },
  {
    id: "3.08",
    category: "營運",
    project: "project-assistant",
    name: "整合資訊",
    description: "",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },
  {
    id: "3.09",
    category: "營運",
    project: "project-assistant",
    name: "判斷重複",
    description: "",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },
  {
    id: "3.10",
    category: "營運",
    project: "project-assistant",
    name: "自動更新",
    description: "",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },

  // ── 培訓 / video-review ──────────────────────────────────────────────────
  {
    id: "4.01",
    category: "培訓",
    project: "video-review",
    name: "處理影片回顧",
    description:
      "Input: User-provided video file or the transcript.\n\nProcess: Transcribe the video, remove filler words, and map the content to the reference outline (strictly ignoring reference text detail).\n\nOutput: A reader-friendly document structured into Summary, Theme, Q&A, Tools, and Call to Action sections.",
    input: "User-provided video file or the transcript.",
    process: "Transcribe the video, remove filler words, and map the content to the reference outline (strictly ignoring reference text detail).",
    output: "A reader-friendly document structured into Summary, Theme, Q&A, Tools, and Call to Action sections.",
    synergy: [],
    platform: "multi",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "11/27",
  },

  // ── AI 助理開發 / prompt-engineering ────────────────────────────────────
  {
    id: "5.01",
    category: "AI 助理開發",
    project: "prompt-engineering",
    name: "指令工程助理 ─ 引導產品需求",
    description: "",
    synergy: ["5.01", "5.02"],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },
  {
    id: "5.02",
    category: "AI 助理開發",
    project: "prompt-engineering",
    name: "指令工程助理 ─ 重構指令",
    description:
      "Input: User provides a prompt to optimize.\n\nProcess: Apply GUIDE and IPO, clarify only when needed, restructure into system/developer/user layers, and define goals, reasoning steps, and output format.\n\nOutput: A clear, testable prompt package with explicit roles, instructions, and structure, plus variants or blueprints when useful.",
    input: "User provides a prompt to optimize.",
    process: "Apply GUIDE and IPO, clarify only when needed, restructure into system/developer/user layers, and define goals, reasoning steps, and output format.",
    output: "A clear, testable prompt package with explicit roles, instructions, and structure, plus variants or blueprints when useful.",
    synergy: ["5.01", "5.02"],
    platform: "multi",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "12/8",
  },

  // ── 人才發展 / recruitment ───────────────────────────────────────────────
  {
    id: "7.01",
    category: "人才發展",
    project: "recruitment",
    name: "招募助理 ─ 對齊職務需求",
    description:
      "Input: Hiring manager provides rough notes or ideas about the role.\n\nProcess: Assistant asks structured clarifying questions and guides the user through a JD-creation workflow.\n\nOutput: A complete JD draft in YAML with versioning and an optional alignment summary.",
    input: "Hiring manager provides rough notes or ideas about the role.",
    process: "Assistant asks structured clarifying questions and guides the user through a JD-creation workflow.",
    output: "A complete JD draft in YAML with versioning and an optional alignment summary.",
    synergy: ["7.01", "7.02", "7.03", "7.04", "7.05"],
    platform: "gpt",
    status: "Done",
    author: "Jane Liao",
    updatedAt: "10/28",
  },
  {
    id: "7.02",
    category: "人才發展",
    project: "recruitment",
    name: "招募助理 ─ 履歷篩選",
    description:
      "Input: JD criteria, one or more candidate resumes, optional company culture notes, and optional desired shortlist size.\n\nProcess: Decode JD → analyze resumes → score candidates using hard-skill gate, domain fit, weighted metrics, and risk indicators.\n\nOutput: Ranked candidate evaluation with scores, risks, cultural fit notes, and a final HR decision summary.",
    input: "JD criteria, one or more candidate resumes, optional company culture notes, and optional desired shortlist size.",
    process: "Decode JD → analyze resumes → score candidates using hard-skill gate, domain fit, weighted metrics, and risk indicators.",
    output: "Ranked candidate evaluation with scores, risks, cultural fit notes, and a final HR decision summary.",
    synergy: ["7.01", "7.02", "7.03", "7.04", "7.05"],
    platform: "gpt",
    status: "Done",
    author: "Jane Liao",
    updatedAt: "11/5",
  },
  {
    id: "7.03",
    category: "人才發展",
    project: "recruitment",
    name: "招募助理 ─ 設計考題與計分卡",
    description:
      "Input: JD Blueprint, competency requirements, role context, and candidate risk insights (from resume screening).\n\nProcess: Convert role requirements into a competency model → assign competencies to interview rounds → generate structured question bank (behavioral, situational, technical, culture) → produce tailored risk-based questions → build weighted scorecard with behavioral indicators and scoring anchors.\n\nOutput: A complete bilingual interview kit including competency model, question sets, risk questions, scoring rubrics, and a finalized scorecard ready for interviewers to use.",
    input: "JD Blueprint, competency requirements, role context, and candidate risk insights (from resume screening).",
    process: "Convert role requirements into a competency model → assign competencies to interview rounds → generate structured question bank (behavioral, situational, technical, culture) → produce tailored risk-based questions → build weighted scorecard with behavioral indicators and scoring anchors.",
    output: "A complete bilingual interview kit including competency model, question sets, risk questions, scoring rubrics, and a finalized scorecard ready for interviewers to use.",
    synergy: ["7.01", "7.02", "7.03", "7.04", "7.05"],
    platform: "gpt",
    status: "Done",
    author: "Jane Liao",
    updatedAt: "11/27",
  },
  {
    id: "7.04",
    category: "人才發展",
    project: "recruitment",
    name: "招募助理 ─ 面試評分校準與決策",
    description:
      "Input: Interview transcripts, interviewer scorecards, Assistant A's question set and scoring standards, and hiring manager/HR inputs.\n\nProcess: Extract behavioral evidence → compile independent feedback → detect discrepancies across interviewers → prepare pre-calibration summaries → support calibration discussions → document final hire/no-hire decisions with rationale and risk considerations.\n\nOutput: A structured final evaluation package including evidence summaries, discrepancy analysis, calibration notes, final decision record, and candidate communication guidelines.",
    input: "Interview transcripts, interviewer scorecards, Assistant A's question set and scoring standards, and hiring manager/HR inputs.",
    process: "Extract behavioral evidence → compile independent feedback → detect discrepancies across interviewers → prepare pre-calibration summaries → support calibration discussions → document final hire/no-hire decisions with rationale and risk considerations.",
    output: "A structured final evaluation package including evidence summaries, discrepancy analysis, calibration notes, final decision record, and candidate communication guidelines.",
    synergy: ["7.01", "7.02", "7.03", "7.04", "7.05"],
    platform: "gpt",
    status: "Done",
    author: "Jane Liao",
    updatedAt: "11/27",
  },
  {
    id: "7.05",
    category: "人才發展",
    project: "recruitment",
    name: "招募助理 ─ 候選人溝通",
    description:
      "Input: Candidate information, hiring stage, interview details (if applicable), and any specific instructions regarding tone or language preference.\n\nProcess: Auto-detect communication scenario → classify risk level → check required information → generate a compliant formal email using structured templates and context-aware tone → provide optional refinements.\n\nOutput: A polished, risk-compliant, formal business email (Chinese, English, or bilingual), fully personalized and ready to send.",
    input: "Candidate information, hiring stage, interview details (if applicable), and any specific instructions regarding tone or language preference.",
    process: "Auto-detect communication scenario → classify risk level → check required information → generate a compliant formal email using structured templates and context-aware tone → provide optional refinements.",
    output: "A polished, risk-compliant, formal business email (Chinese, English, or bilingual), fully personalized and ready to send.",
    synergy: ["7.01", "7.02", "7.03", "7.04", "7.05"],
    platform: "gpt",
    status: "WIP",
    author: "Jane Liao",
    updatedAt: "11/23",
  },

  // ── 培訓 / course-ta ─────────────────────────────────────────────────────
  {
    id: "7.06",
    category: "培訓",
    project: "course-ta",
    name: "課程助教 ─ 寫作及與 AI 互動的技巧",
    description:
      "Input: Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.\n\nProcess: Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.\n\nOutput: Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    input: "Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.",
    process: "Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.",
    output: "Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "11/2",
  },
  {
    id: "7.07",
    category: "培訓",
    project: "course-ta",
    name: "課程助教 ─ 打造寫作系統的底層邏輯",
    description:
      "Input: Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.\n\nProcess: Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.\n\nOutput: Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    input: "Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.",
    process: "Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.",
    output: "Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "11/2",
  },
  {
    id: "7.08",
    category: "培訓",
    project: "course-ta",
    name: "課程助教 ─ 打造寫作助理實作",
    description:
      "Input: Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.\n\nProcess: Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.\n\nOutput: Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    input: "Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.",
    process: "Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.",
    output: "Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "11/2",
  },
  {
    id: "7.09",
    category: "培訓",
    project: "course-ta",
    name: "課程助教 ─ 協助學員打造客製化助理",
    description:
      "Input: Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.\n\nProcess: Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.\n\nOutput: Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    input: "Student questions or answers about AI writing concepts from the course, or a request to be quizzed or taught.",
    process: "Apply course frameworks to quiz, evaluate, or explain through guided questioning and structured feedback.",
    output: "Scored assessments or clear, practical explanations that deepen understanding and improve AI-assisted writing skills.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "11/2",
  },
  {
    id: "7.10",
    category: "培訓",
    project: "course-ta",
    name: "課程助教 ─ 學員評估",
    description: "",
    synergy: [],
    platform: "gpt",
    status: "Not started",
    author: "Peter Tu",
  },
  {
    id: "7.11",
    category: "培訓",
    project: "course-ta",
    name: "課程助教 ─ 終極升遷指南第二章",
    description:
      "Input: User's career-related question or unclear bottleneck tied to the course content.\n\nProcess: Clarify the situation, map it to the course's eight principles, and reason strictly from the provided transcript.\n\nOutput: A validated interpretation, relevant principle alignment, and a concrete next action grounded in the course.",
    input: "User's career-related question or unclear bottleneck tied to the course content.",
    process: "Clarify the situation, map it to the course's eight principles, and reason strictly from the provided transcript.",
    output: "A validated interpretation, relevant principle alignment, and a concrete next action grounded in the course.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
    updatedAt: "1/15",
  },
  {
    id: "7.12",
    category: "培訓",
    project: "course-ta",
    name: "課程助教 ─ 策略規劃助理",
    description:
      "Input: User's career background, constraints, goals, preferences, and reflections provided through guided questions.\n\nProcess: Structured, stage-based coaching—ask clarifying questions, synthesize answers, propose options, validate choices, and iteratively refine strategy.\n\nOutput: A clear 3-year vision, 3–5 strategic pillars, RAG assessments with upgrade hypotheses, and one prioritized one-page project charter.",
    input: "User's career background, constraints, goals, preferences, and reflections provided through guided questions.",
    process: "Structured, stage-based coaching—ask clarifying questions, synthesize answers, propose options, validate choices, and iteratively refine strategy.",
    output: "A clear 3-year vision, 3–5 strategic pillars, RAG assessments with upgrade hypotheses, and one prioritized one-page project charter.",
    synergy: [],
    platform: "gpt",
    status: "Done",
    author: "Peter Tu",
  },

  // ── 業務顧問 / sales-assistant ───────────────────────────────────────────
  {
    id: "8.01",
    category: "業務顧問",
    project: "sales-assistant",
    name: "業務助理 ─ 名片整理",
    description:
      "Input: User background information (professional role, services or expertise) and one or more business cards (image or text).\n\nProcess: Extract and normalize only the information explicitly visible on each business card, handling incomplete or noisy inputs without fabrication. Capture uncertainty and missing fields for later enrichment, while keeping all non-visible attributes empty.\n\nOutput: Structured lead records aligned with the master sheet schema, containing clean contact details, remarks on uncertainty, and placeholders for downstream enrichment and scoring.",
    input: "User background information (professional role, services or expertise) and one or more business cards (image or text).",
    process: "Extract and normalize only the information explicitly visible on each business card, handling incomplete or noisy inputs without fabrication. Capture uncertainty and missing fields for later enrichment, while keeping all non-visible attributes empty.",
    output: "Structured lead records aligned with the master sheet schema, containing clean contact details, remarks on uncertainty, and placeholders for downstream enrichment and scoring.",
    synergy: [],
    platform: "gpt",
    status: "WIP",
    author: "Jane Liao",
  },
  {
    id: "8.02",
    category: "業務顧問",
    project: "sales-assistant",
    name: "業務助理 ─ 線索評分助理",
    description:
      "Input: A single lead record from the master sheet (identity, contact details, enrichment data, and optional sales context).\n\nProcess: Evaluate ICP fit, buying intent, role relevance, and recency using conservative scoring rules with anti-inflation guardrails. Apply score caps, penalties, and flags to determine realistic priority.\n\nOutput: A scored lead record with a priority tier, action recommendation, key reasons, and confidence level for first-touch outreach.",
    input: "A single lead record from the master sheet (identity, contact details, enrichment data, and optional sales context).",
    process: "Evaluate ICP fit, buying intent, role relevance, and recency using conservative scoring rules with anti-inflation guardrails. Apply score caps, penalties, and flags to determine realistic priority.",
    output: "A scored lead record with a priority tier, action recommendation, key reasons, and confidence level for first-touch outreach.",
    synergy: [],
    platform: "gpt",
    status: "WIP",
    author: "Jane Liao",
  },
];
