/**
 * Walks `skills/[N]-[category]/[slug]/` and writes a markdown tree into
 * `skills/README.md` between the TREE:START / TREE:END markers.
 *
 * Each node is labelled from the skill's OWN SKILL.md frontmatter (the
 * authoritative source) and falls back to `generated/skills-detail.json`
 * (the catalog the marketplace renders) when a folder has no root SKILL.md
 * — e.g. an orchestrator sourced from CLAUDE.md. So the tree mirrors
 * https://zynkr.ai/ai-skills-marketplace in the normal case. Each node shows:
 *
 *   <sheetId> <name>   ✓ <description>  +agents
 *   <sheetId> <name> (<folder-slug>/)   ✓ ...   ← only when slug ≠ name (drift)
 *
 * The `(<folder-slug>/)` column is a quiet drift flag: it renders ONLY when the
 * folder slug differs from the display name. The convention is that they match
 * (frontmatter `name` is canonical — folder, project, slug and name are kept in
 * lockstep), so the column normally collapses and the page stays clean; it
 * re-appears the moment a new/renamed skill drifts. Within a category, skills
 * are ordered by sheetId.
 *
 * Beyond the missing/short/title-description checks, the tree flags genuine
 * source↔catalog drift so the README stays honest:
 *   - sheetId prefix ≠ category folder number (mis-numbered or misfiled)
 *   - frontmatter `project` ≠ folder slug (causes an ingest slug collision)
 *   - catalog name ≠ source name (collision winner / stale catalog)
 *
 * Run: `npm run build-tree` (from scripts/). The ingest workflow runs this
 * automatically after build-marketplace on every push to skills/**.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const SKILLS_DIR = join(REPO_ROOT, 'skills');
const README = join(SKILLS_DIR, 'README.md');
const CATALOG = join(REPO_ROOT, 'generated', 'skills-detail.json');

const START = '<!-- TREE:START — auto-generated by scripts/build-taxonomy-tree.ts, do not edit -->';
const END = '<!-- TREE:END -->';

type Issue = { code: string; label: string; detail: string };
type CatalogEntry = { name: string; sheetId: string; summary: string; kind: string };
type Skill = {
  slug: string;          // folder name = frozen canonical id
  displayName: string;   // marketplace name (frontmatter `name`)
  sheetId: string;       // chronological number, or '' if unset
  description: string;
  hasSkillMd: boolean;
  hasAgents: boolean;
  inCatalog: boolean;
  issues: Issue[];
};
type Category = { dir: string; num: string; key: string; skills: Skill[] };

function listDirs(path: string): string[] {
  return readdirSync(path)
    .filter(name => statSync(join(path, name)).isDirectory())
    .sort();
}

function listFiles(path: string): string[] {
  return readdirSync(path).filter(name => statSync(join(path, name)).isFile());
}

const TITLE_RE = /^\s*\d+\s+[—\-:]\s+\S/;

/**
 * Map folder slug (catalog `project`) -> the parent record's display fields.
 * Parent = the record whose source_path is NOT under an `/agents/` dir.
 */
function loadCatalog(): { map: Map<string, CatalogEntry>; total: number } {
  const map = new Map<string, CatalogEntry>();
  if (!existsSync(CATALOG)) return { map, total: 0 };
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(CATALOG, 'utf-8'));
  } catch {
    return { map, total: 0 };
  }
  const rows: any[] = Array.isArray(raw) ? raw : Object.values(raw as object);
  for (const r of rows) {
    const project = (r?.project ?? '').toString();
    const sp = (r?.source_path ?? '').toString();
    if (!project || sp.includes('/agents/')) continue; // only parents map to a folder node
    if (!map.has(project)) {
      map.set(project, {
        name: (r?.name ?? '').toString().trim(),
        sheetId: (r?.sheet_id ?? '').toString().trim(),
        summary: (r?.summary ?? '').toString().trim(),
        kind: (r?.kind ?? '').toString().trim(),
      });
    }
  }
  return { map, total: rows.length };
}

function readSkill(skillDir: string, slug: string, catNum: string, cat: CatalogEntry | undefined): Skill {
  const skillMd = join(skillDir, 'SKILL.md');
  const hasSkillMd = existsSync(skillMd);
  const hasAgents = existsSync(join(skillDir, 'agents'));
  const inCatalog = !!cat;
  const issues: Issue[] = [];

  let fmName = '';
  let fmSheetId = '';
  let fmProject = '';
  let desc = '';

  if (hasSkillMd) {
    try {
      const { data } = matter(readFileSync(skillMd, 'utf-8'));
      fmName = (data?.name ?? '').toString().trim();
      fmSheetId = (data?.sheetId ?? '').toString().trim();
      fmProject = (data?.project ?? '').toString().trim();
      desc = (data?.description ?? '').toString().trim();

      if (!desc) {
        issues.push({ code: 'no-description', label: 'no description in frontmatter', detail: 'add a `description:` line with a usage-oriented sentence' });
      } else if (desc.length < 40) {
        issues.push({ code: 'short-description', label: 'description shorter than 40 chars', detail: `current: "${desc}"` });
      } else if (TITLE_RE.test(desc)) {
        issues.push({ code: 'title-as-description', label: 'description looks like a title', detail: `current: "${desc}" — replace with a usage-oriented sentence` });
      }

      // Drift checks (only meaningful when we can read the source).
      if (fmProject && fmProject !== slug) {
        issues.push({
          code: 'project-folder-mismatch',
          label: 'frontmatter `project` ≠ folder name',
          detail: `declares \`project: ${fmProject}\` but lives in \`${slug}/\` — collides with the ${fmProject} skill in ingest (one swallows the other)`,
        });
      }
      if (inCatalog && fmName && cat!.name && fmName !== cat!.name) {
        issues.push({
          code: 'catalog-source-divergence',
          label: 'catalog name ≠ source name',
          detail: `marketplace shows "${cat!.name}" but source declares "${fmName}" (ingest collision winner or stale catalog)`,
        });
      }
    } catch (err) {
      issues.push({ code: 'unreadable-frontmatter', label: 'frontmatter could not be parsed', detail: (err as Error).message });
    }
  } else if (!inCatalog) {
    // Genuinely broken: no SKILL.md at the folder root AND not in the catalog.
    const siblings = listFiles(skillDir).filter(f => f !== '.DS_Store');
    const subdirs = listDirs(skillDir);
    const present = [...siblings, ...subdirs.map(d => `${d}/`)].join(', ') || 'empty folder';
    issues.push({ code: 'missing-skill-md', label: 'missing SKILL.md', detail: `folder contains ${present}` });
  }
  // No SKILL.md but IS in the catalog (e.g. orchestrator ingested from CLAUDE.md) — valid.

  const displayName = fmName || cat?.name || slug;
  const sheetId = fmSheetId || cat?.sheetId || '';
  const description =
    desc || cat?.summary || (inCatalog ? '_(no description — see marketplace)_' : '_Missing SKILL.md_');

  // sheetId prefix should match the category folder number.
  if (sheetId) {
    const major = sheetId.split('.')[0];
    if (catNum && major && major !== catNum) {
      issues.push({
        code: 'number-category-mismatch',
        label: 'sheetId prefix ≠ category folder',
        detail: `numbered ${sheetId} (prefix ${major}) but filed under ${catNum}-* — renumber it or move the folder`,
      });
    }
  }

  return { slug, displayName, sheetId, description, hasSkillMd, hasAgents, inCatalog, issues };
}

function sheetKey(s: string): [number, number] {
  if (!s) return [Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY];
  const [a, b] = s.split('.');
  return [parseInt(a, 10) || 0, parseInt(b ?? '', 10) || 0];
}

function truncate(s: string, max = 80): string {
  const flat = s.replace(/\s+/g, ' ').trim();
  return flat.length > max ? flat.slice(0, max - 1).trimEnd() + '…' : flat;
}

function collect(catalog: Map<string, CatalogEntry>): Category[] {
  return listDirs(SKILLS_DIR)
    .filter(name => /^\d+-/.test(name))
    .map(dir => {
      const [num, ...rest] = dir.split('-');
      const key = rest.join('-');
      const skills = listDirs(join(SKILLS_DIR, dir)).map(slug =>
        readSkill(join(SKILLS_DIR, dir, slug), slug, num, catalog.get(slug))
      );
      skills.sort((a, b) => {
        const [am, an] = sheetKey(a.sheetId);
        const [bm, bn] = sheetKey(b.sheetId);
        if (am !== bm) return am - bm;
        if (an !== bn) return an - bn;
        return a.slug.localeCompare(b.slug);
      });
      return { dir, num, key, skills };
    });
}

function badge(skill: Skill): string {
  return skill.issues.length > 0 ? '⚠' : '✓';
}

function tags(skill: Skill): string {
  return skill.hasAgents ? ' +agents' : '';
}

function pad(s: string, width: number): string {
  return s.length >= width ? s + ' ' : s + ' '.repeat(width - s.length);
}

function renderTree(categories: Category[]): string {
  const lines: string[] = [];
  lines.push('```text');
  lines.push('skills/');

  const lastCatIdx = categories.length - 1;
  categories.forEach((cat, ci) => {
    const isLastCat = ci === lastCatIdx;
    const catPrefix = isLastCat ? '└── ' : '├── ';
    const childIndent = isLastCat ? '    ' : '│   ';

    if (cat.skills.length === 0) {
      lines.push(`${catPrefix}${cat.dir}/${' '.repeat(Math.max(1, 38 - cat.dir.length - 1))}(empty)`);
      return;
    }

    lines.push(`${catPrefix}${cat.dir}/`);
    cat.skills.forEach((skill, si) => {
      const isLastSkill = si === cat.skills.length - 1;
      const skillPrefix = isLastSkill ? '└── ' : '├── ';
      const numCol = pad(skill.sheetId || '—', 5);
      // Folder-slug column only renders on drift (slug ≠ display name) — a
      // quiet drift flag. When they match (the norm), collapse it so the name
      // spans the full width and the description column stays aligned.
      const drift = skill.slug !== skill.displayName;
      const nameBlock = drift
        ? `${pad(skill.displayName, 26)}${pad(`(${skill.slug}/)`, 24)}`
        : pad(skill.displayName, 50);
      const left = `${childIndent}${skillPrefix}${numCol}${nameBlock}`;
      const right = `${badge(skill)} ${truncate(skill.description, 48)}${tags(skill)}`;
      lines.push(`${left}${right}`);
    });
  });

  lines.push('```');
  return lines.join('\n');
}

function renderCallouts(categories: Category[]): string {
  const flagged: { path: string; skill: Skill }[] = [];
  for (const cat of categories) {
    for (const s of cat.skills) {
      if (s.issues.length > 0) flagged.push({ path: `${cat.dir}/${s.slug}`, skill: s });
    }
  }

  const lines: string[] = [];
  lines.push('### Status callouts');
  lines.push('');
  if (flagged.length === 0) {
    lines.push('_No issues — every skill resolves to a catalog entry with a usable description._');
    return lines.join('\n');
  }
  for (const { path, skill } of flagged) {
    for (const issue of skill.issues) {
      lines.push(`- ⚠ \`${path}\` — **${issue.label}**: ${issue.detail}`);
    }
  }
  return lines.join('\n');
}

function render(categories: Category[], catalogTotal: number): string {
  const total = categories.reduce((n, c) => n + c.skills.length, 0);
  const populated = categories.filter(c => c.skills.length > 0).length;
  const issueCount = categories.reduce((n, c) => n + c.skills.filter(s => s.issues.length > 0).length, 0);

  const lines: string[] = [];
  const issueNote = issueCount === 0 ? 'no issues flagged' : `${issueCount} issue${issueCount === 1 ? '' : 's'} flagged`;
  const catalogNote = catalogTotal ? ` · ${catalogTotal} catalog entries incl. agents` : '';
  lines.push(
    `_${total} skill folders across ${categories.length} categories (${populated} populated)${catalogNote} — ${issueNote}. Numbers & names mirror the [marketplace](https://zynkr.ai/ai-skills-marketplace); folder slug = frozen install id._`
  );
  lines.push('');
  lines.push(renderTree(categories));
  lines.push('');
  lines.push(renderCallouts(categories));
  lines.push('');

  return lines.join('\n').trimEnd() + '\n';
}

function splice(readme: string, body: string): string {
  const startIdx = readme.indexOf(START);
  const endIdx = readme.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `Markers not found in ${README}. Add this section to the README first:\n\n## Skill tree\n\n${START}\n${END}\n`
    );
  }
  const before = readme.slice(0, startIdx + START.length);
  const after = readme.slice(endIdx);
  return `${before}\n\n${body}\n${after}`;
}

function main() {
  const { map: catalog, total: catalogTotal } = loadCatalog();
  const categories = collect(catalog);
  const body = render(categories, catalogTotal);
  const current = readFileSync(README, 'utf-8');
  const next = splice(current, body);
  if (next === current) {
    console.log('Taxonomy tree unchanged.');
    return;
  }
  writeFileSync(README, next, 'utf-8');
  const total = categories.reduce((n, c) => n + c.skills.length, 0);
  const flagged = categories.reduce((n, c) => n + c.skills.filter(s => s.issues.length > 0).length, 0);
  console.log(`Updated ${README} — ${categories.length} categories, ${total} folders, ${catalogTotal} catalog entries, ${flagged} flagged.`);
}

main();
