/**
 * Walks `skills/[N]-[category]/[slug]/SKILL.md` and writes a markdown tree
 * into `skills/README.md` between the TREE:START / TREE:END markers.
 *
 * Output layout:
 *   1. ASCII tree of `skills/` with one-line description per skill and a
 *      status badge (✓ / ⚠) — empty categories shown as `(empty)`.
 *   2. Status callouts section listing every flagged skill with the issue
 *      and suggested fix.
 *
 * Run: `npm run build-tree` (from scripts/). The ingest workflow runs this
 * automatically after every push to skills/**.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const SKILLS_DIR = join(REPO_ROOT, 'skills');
const README = join(SKILLS_DIR, 'README.md');

const START = '<!-- TREE:START — auto-generated by scripts/build-taxonomy-tree.ts, do not edit -->';
const END = '<!-- TREE:END -->';

type Issue = { code: string; label: string; detail: string };
type Skill = {
  slug: string;
  description: string;
  hasSkillMd: boolean;
  hasAgents: boolean;
  issues: Issue[];
};
type Category = { dir: string; num: string; key: string; skills: Skill[] };

function listDirs(path: string): string[] {
  return readdirSync(path)
    .filter(name => statSync(join(path, name)).isDirectory())
    .sort();
}

function listFiles(path: string): string[] {
  return readdirSync(path).filter(name => statSync(join(path, name)).isFile());
}

const TITLE_RE = /^\s*\d+\s+[—\-:]\s+\S/;

function readSkill(skillDir: string, slug: string): Skill {
  const skillMd = join(skillDir, 'SKILL.md');
  const hasSkillMd = existsSync(skillMd);
  const hasAgents = existsSync(join(skillDir, 'agents'));
  const issues: Issue[] = [];

  if (!hasSkillMd) {
    const siblings = listFiles(skillDir).filter(f => f !== '.DS_Store');
    const subdirs = listDirs(skillDir);
    const present = [...siblings, ...subdirs.map(d => `${d}/`)].join(', ') || 'empty folder';
    issues.push({
      code: 'missing-skill-md',
      label: 'missing SKILL.md',
      detail: `folder contains ${present}`,
    });
    return { slug, description: '_Missing SKILL.md_', hasSkillMd, hasAgents, issues };
  }

  try {
    const { data } = matter(readFileSync(skillMd, 'utf-8'));
    const desc = (data?.description ?? '').toString().trim();

    if (!desc) {
      issues.push({
        code: 'no-description',
        label: 'no description in frontmatter',
        detail: 'add a `description:` line with a usage-oriented sentence',
      });
    } else if (desc.length < 40) {
      issues.push({
        code: 'short-description',
        label: 'description shorter than 40 chars',
        detail: `current: "${desc}"`,
      });
    } else if (TITLE_RE.test(desc)) {
      issues.push({
        code: 'title-as-description',
        label: 'description looks like a title',
        detail: `current: "${desc}" — replace with a usage-oriented sentence`,
      });
    }

    return {
      slug,
      description: desc || '_No description_',
      hasSkillMd,
      hasAgents,
      issues,
    };
  } catch (err) {
    issues.push({
      code: 'unreadable-frontmatter',
      label: 'frontmatter could not be parsed',
      detail: (err as Error).message,
    });
    return { slug, description: '_Unreadable frontmatter_', hasSkillMd, hasAgents, issues };
  }
}

function truncate(s: string, max = 80): string {
  const flat = s.replace(/\s+/g, ' ').trim();
  return flat.length > max ? flat.slice(0, max - 1).trimEnd() + '…' : flat;
}

function collect(): Category[] {
  return listDirs(SKILLS_DIR)
    .filter(name => /^\d+-/.test(name))
    .map(dir => {
      const [num, ...rest] = dir.split('-');
      const key = rest.join('-');
      const skills = listDirs(join(SKILLS_DIR, dir)).map(slug =>
        readSkill(join(SKILLS_DIR, dir, slug), slug)
      );
      return { dir, num, key, skills };
    });
}

function badge(skill: Skill): string {
  if (skill.issues.length > 0) return '⚠';
  return '✓';
}

function tags(skill: Skill): string {
  return skill.hasAgents ? ' +agents' : '';
}

function pad(s: string, width: number): string {
  return s.length >= width ? s + ' ' : s + ' '.repeat(width - s.length);
}

function renderTree(categories: Category[]): string {
  const lines: string[] = [];
  lines.push('```text');
  lines.push('skills/');

  const lastCatIdx = categories.length - 1;
  categories.forEach((cat, ci) => {
    const isLastCat = ci === lastCatIdx;
    const catPrefix = isLastCat ? '└── ' : '├── ';
    const childIndent = isLastCat ? '    ' : '│   ';

    if (cat.skills.length === 0) {
      lines.push(`${catPrefix}${cat.dir}/${' '.repeat(Math.max(1, 38 - cat.dir.length - 1))}(empty)`);
      return;
    }

    lines.push(`${catPrefix}${cat.dir}/`);
    cat.skills.forEach((skill, si) => {
      const isLastSkill = si === cat.skills.length - 1;
      const skillPrefix = isLastSkill ? '└── ' : '├── ';
      const name = `${skill.slug}/`;
      const left = `${childIndent}${skillPrefix}${pad(name, 34)}`;
      const right = `${badge(skill)} ${truncate(skill.description, 70)}${tags(skill)}`;
      lines.push(`${left}${right}`);
    });
  });

  lines.push('```');
  return lines.join('\n');
}

function renderCallouts(categories: Category[]): string {
  const flagged: { path: string; skill: Skill }[] = [];
  for (const cat of categories) {
    for (const s of cat.skills) {
      if (s.issues.length > 0) flagged.push({ path: `${cat.dir}/${s.slug}`, skill: s });
    }
  }

  const lines: string[] = [];
  lines.push('### Status callouts');
  lines.push('');
  if (flagged.length === 0) {
    lines.push('_No issues — every skill has a SKILL.md with a usable description._');
    return lines.join('\n');
  }
  for (const { path, skill } of flagged) {
    for (const issue of skill.issues) {
      lines.push(`- ⚠ \`${path}\` — **${issue.label}**: ${issue.detail}`);
    }
  }
  return lines.join('\n');
}

function render(categories: Category[]): string {
  const total = categories.reduce((n, c) => n + c.skills.length, 0);
  const populated = categories.filter(c => c.skills.length > 0).length;
  const issueCount = categories.reduce(
    (n, c) => n + c.skills.filter(s => s.issues.length > 0).length,
    0
  );

  const lines: string[] = [];
  const issueNote = issueCount === 0 ? 'no issues flagged' : `${issueCount} issue${issueCount === 1 ? '' : 's'} flagged`;
  lines.push(
    `_${total} skills across ${categories.length} categories (${populated} populated) — ${issueNote}._`
  );
  lines.push('');
  lines.push(renderTree(categories));
  lines.push('');
  lines.push(renderCallouts(categories));
  lines.push('');

  return lines.join('\n').trimEnd() + '\n';
}

function splice(readme: string, body: string): string {
  const startIdx = readme.indexOf(START);
  const endIdx = readme.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      `Markers not found in ${README}. Add this section to the README first:\n\n## Skill tree\n\n${START}\n${END}\n`
    );
  }
  const before = readme.slice(0, startIdx + START.length);
  const after = readme.slice(endIdx);
  return `${before}\n\n${body}\n${after}`;
}

function main() {
  const categories = collect();
  const body = render(categories);
  const current = readFileSync(README, 'utf-8');
  const next = splice(current, body);
  if (next === current) {
    console.log('Taxonomy tree unchanged.');
    return;
  }
  writeFileSync(README, next, 'utf-8');
  const total = categories.reduce((n, c) => n + c.skills.length, 0);
  const flagged = categories.reduce((n, c) => n + c.skills.filter(s => s.issues.length > 0).length, 0);
  console.log(
    `Updated ${README} — ${categories.length} categories, ${total} skills, ${flagged} flagged.`
  );
}

main();
